services:
  postgres:
    container_name: postgres-sql-whatsapp
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=whatsapp-db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - network-whatsapp
    restart: unless-stopped

  keycloak:
    container_name: keycloak-whatsapp
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 9093:8080
    networks:
      - network-whatsapp
    command:
      - "start-dev"

networks:
  network-whatsapp:
    driver: bridge

volumes:
  postgres:
    driver: local